version: '3.8'

services:
  frontend:
    image: komo04/felsimfront:${VERSION}
    ports: 
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - VITE_BACKEND_API_PORT=${BACKEND_API_PORT}
    depends_on:
      - backend       # Ensure the backend service is started before the frontend
    

  backend:
    image: komo04/felsimback:${VERSION}
    ports:
      - "${BACKEND_API_PORT}:${BACKEND_API_PORT}"
    environment:
      - BACKEND_API_PORT=${BACKEND_API_PORT}
      - BACKEND_API_IP=${BACKEND_API_IP}
      - FRONTEND_PORT=${FRONTEND_PORT}
